import React from 'react';
import { Form, Input } from 'antd';
export default {
    title    : 'Ant/Forms/ExtraStyles',
    component: Input,
};
const Template = (args) => {
    const { TextArea } = Input;

    return (
        <Form layout="horizontal" style={{ width: '400px' }}>
            <Form.Item
                label="Input"
                name="input0"
            >
                <Input
                    placeholder="Placeholder"
                    allowClear={true}
                />
            </Form.Item>

            <div className="autogenerated-block">
                <Form.Item
                    label="Input"
                    name="input1"
                >
                    <Input
                        defaultValue="Calculated value"
                        placeholder="Placeholder"
                        readOnly
                        className="autogenerated"
                    />
                </Form.Item>

                <Form.Item
                    label="Autogenerated"
                    name="input3"
                >
                    <TextArea
                        defaultValue="Calculated value. Always readonly. Requires 'autogenerated' class"
                        placeholder="Placeholder"
                        readOnly
                        className="autogenerated"
                        autoSize={{ minRows: 1, maxRows: 3 }}
                    />
                </Form.Item>
            </div>
        </Form>
    );
};

export const AutogeneratedBlock = Template.bind({});
AutogeneratedBlock.args = {
};